function [] = piv(param_json, prep_mat, piv_mat)
% function [] = piv(param_json, prep_mat, piv_mat)
% 
% Run PIV analysis for a given image series. Simple wrapper around
% piv_series() that reads the (many) input parameters from the standard
% JSON file rather than as arguments.
%
% Arguments:
% 
%   param_json: JSON file containing all input parameters
% 
%   prep_mat = String, filename of the MAT file containing pre-processed
%       experiment images
% 
%   piv_mat = String, filename of the MAT file to be created.
% %

update_path('jsonlab', 'piv');
param = loadjson(param_json, 'SimplifyCell', 1);
piv_series(...
    piv_mat, ...
    prep_mat, ...
    param.step_range.value, ...
    param.gap.value, ...
    param.samp_len.value, ...
    param.samp_spc.value, ...
    param.intr_len.value, ...
    param.num_pass.value, ...
    param.valid_radius.value, ...
    param.valid_max.value, ...
    param.valid_eps.value, ...
    param.min_frac_data.value, ...
    param.min_frac_overlap.value, ...
    param.notes.value);
