function [] = piv_test_run_image()
%
% Run a hard-coded test case using a synthetic image pair as generated by
% piv_test_create_image.
%
% %

%% parameters

% image parameters
tform = [1, 0.15,   10;  
         0.15,  1,  10];
bnd_mean = 1.1;
bnd_ampl = 0;
bnd_freq = 1;

% piv parameters
samplen = 30;
sampspc = 30;
intrlen = 100;
npass = 1;
valid_max = 2;
valid_eps = 0.01;

%% generate test images

[ini, fin, ini_roi, fin_roi, xx, yy] = ...
    piv_test_create_image(tform, bnd_mean, bnd_ampl, bnd_freq);