function [] = piv_test_run_synth()
%
% Run a hard-coded test case using a synthetic image pair as generated by
% piv_test_create_synth.
%
% %

%% parameters

% synthetic image parameters
img_size = [500, 500];
tform = [1, 0, 0;  
         0, 1, 0];
min_spc = 3;
prob_white = 0.5;
ampl_white = 1;
ampl_black = -1;
sigma = 3;
max_attempts = 1e2;
bnd_mean = 1.1;
bnd_ampl = 0;
bnd_freq = 1;

% piv parameters
samplen = 30;
sampspc = 15;
intrlen = 100;
npass = 1;
valid_max = 2;
valid_eps = 0.01;

% local parameters
data_file = 'test/synth.mat';

%% generate (or load) test images

% check if defined parameters match saved parameters
try
    F = load(data_file, 'img_size', 'tform', 'min_spc', 'prob_white', ...
        'ampl_white', 'ampl_black', 'sigma', 'max_attempts', 'bnd_mean', ...
        'bnd_ampl', 'bnd_freq');
    same = all(F.img_size == img_size) && ...
        all(F.tform(:) == tform(:)) && ...
        F.min_spc == min_spc && ...
        F.prob_white == prob_white && ...
        F.ampl_white == ampl_white && ...
        F.ampl_black == ampl_black && ...
        F.sigma == sigma && ...
        F.max_attempts == max_attempts && ...
        F.bnd_mean == bnd_mean && ...
        F.bnd_ampl == bnd_ampl && ...
        F.bnd_freq == bnd_freq;
catch
    same = 0;
end

% load PIV input data
if same
    fprintf('parameters are not modified, loading input variables from file\n');
    F = load(data_file, 'ini', 'ini_roi', 'fin', 'fin_roi', 'xx', 'yy');
    ini = F.ini;
    ini_roi = F.ini_roi;
    fin = F.fin;
    fin_roi = F.fin_roi;
    xx = F.xx;
    yy = F.yy;
    
else
    fprintf('Parameters are modified, generating new input variables\n');
    
    [ini, fin, ini_roi, fin_roi, xx, yy] = piv_test_create_synth(...
        img_size, tform, min_spc, prob_white, ampl_white, ampl_black, sigma, ...
        max_attempts, bnd_mean, bnd_ampl, bnd_freq);      
    
    save(data_file, 'img_size', 'tform', 'min_spc', 'prob_white', ...
        'ampl_white', 'ampl_black', 'sigma', 'max_attempts', 'bnd_mean', ...
        'bnd_ampl', 'bnd_freq', 'ini', 'ini_roi', 'fin', 'fin_roi', 'xx', 'yy');

end

clear F

%% run PIV and analyze results

% run piv
[xx, yy, uu, vv] = yalebox_piv(ini, fin, ini_roi, fin_roi, xx, yy, samplen, ...
    sampspc, intrlen, npass, valid_max, valid_eps, 1);

% compute exact solution at output grid points
[xgrid, ygrid] = meshgrid(xx, yy);
[xgrid_defm, ygrid_defm] = piv_test_util_transform(tform, xgrid(:), ygrid(:), 1);
xgrid_defm = reshape(xgrid_defm, size(uu));
ygrid_defm = reshape(ygrid_defm, size(uu));

uu_exact = xgrid_defm-xgrid;
vv_exact = ygrid_defm-ygrid;

% compute errors
uu_error = uu-uu_exact;
vv_error = vv-vv_exact;

% compute strain values
[displ, ~, ~, Dd, ~, ~, ~, ~] = ...
    yalebox_decompose_step(xgrid, ygrid, uu, vv, ~isnan(uu));

% print and plot standard results
piv_test_util_print_error(uu_error, vv_error);
piv_test_util_plot_error(uu_error, vv_error);
piv_test_util_plot(xx, yy, uu, vv, displ, Dd);
