function [] = prep(param, prep_mat)
% function [] = prep(param, prep_mat)
% 
% Pre-process image series for PIV analysis. Reads in the images, rectifies
% and crops, masks, corrects illumination, and saves the results and
% metadata in a MAT file.
%
% Simple wraparamer around prep_series() that reads the (many) input
% parameters from a file/struct rather than as arguments.
%
% Arguments:
% 
%   param: Either (a) string, path to MAT file containing all input
%       parameters, or (b) struct containing same
% 
%   prep_mat = String, filename of the MAT input file to be created. 
% %

update_path('util', 'prep');

switch class(param)
    case 'struct'
        param = param;  % do nothing
    case 'char'
        param = load_param(param);
    otherwise
        error('Unexpected type for input argument "param"');
end

prep_series(...
    prep_mat, ...
    param.image_dir.value, ...
    param.exp_files.value, ...
    param.view.value, ...
    param.woco_xw.value, ...
    param.woco_yw.value, ...
    param.woco_xp.value, ...
    param.woco_yp.value, ...
    param.crop_xlim.value, ...
    param.crop_ylim.value, ...
    param.mask_poly.value, ...
    param.mask_hue_lim.value, ...
    param.mask_value_lim.value, ...
    param.mask_entropy_lim.value, ...
    param.mask_entropy_len.value, ...
    param.mask_morph_open_rad.value, ...
    param.mask_morph_erode_rad.value, ...
    param.intensity_eql_len.value, ...
    param.notes.value);
