function [] = prep_series_from_file(result_file, param_file)
% function [] = prep_series_from_file(result_file, param_file)
% 
% Create PIV input file for a given image series. Reads in the images,
% rectifies and crops, masks, corrects illumination, and saves the results
% and metadata in a netCDF file.
%
% Simple wrapper around prep_series() that reads the (many) input
% parameters from the standard JSON file rather than as arguments.
%
% Arguments:
%   result_file = String, filename of the MAT input file to be created. 
%   param_file: JSON file containing all input parameters
% %

% load dependencies
update_path('jsonlab', 'prep');

% load parameters struct
param = loadjson(param_file, 'SimplifyCell', 1);

% generate missing input parameters
% note: not changed in prep_series in order to maintain backward compat
img = imread(...
    fullfile(param.image_dir.value, param.exp_files.value{1}));
% missing world coordinate vectors
[~, xw, yw] = prep_rectify_and_crop(...
    param.woco_xp.value, ...
    param.woco_yp.value, ...
    param.woco_xw.value, ...
    param.woco_yw.value, ...
    param.crop_xlim.value, ...
    param.crop_ylim.value, ...
    img, ...
    param.crop_npts.value, ...
    false);
% missing manual mask
[mask_manual, ~] = prep_mask_manual(...
    zeros(length(yw), length(xw), 3), ...
    param.mask_poly.value, ...
    false);

% call standard prep_series function
prep_series(...
    result_file, ...
    param.image_dir.value, ...
    param.exp_files.value, ...
    param.view.value, ...
    param.woco_xw.value, ...
    param.woco_yw.value, ...
    param.woco_xp.value, ...
    param.woco_yp.value, ...
    param.crop_xlim.value, ...
    param.crop_ylim.value, ...
    param.crop_npts.value, ...
    param.mask_hue_lim.value, ...
    param.mask_value_lim.value, ...
    param.mask_entropy_lim.value, ...
    param.mask_entropy_len.value, ...
    param.mask_morph_open_rad.value, ...
    param.mask_morph_erode_rad.value, ...
    param.intensity_eql_len.value, ...
    xw, ...
    yw, ...
    mask_manual, ...
    param.notes.value);
