function [] = prep(param_json, prep_mat)
% function [] = prep(param_json, prep_mat)
% 
% Pre-process image series for PIV analysis. Reads in the images, rectifies
% and crops, masks, corrects illumination, and saves the results and
% metadata in a MAT file.
%
% Simple wrapper around prep_series() that reads the (many) input
% parameters from the standard JSON file rather than as arguments.
%
% Arguments:
% 
%   param_json: JSON file containing all input parameters
% 
%   prep_mat = String, filename of the MAT input file to be created. 
% %

update_path('jsonlab', 'prep');
pp = loadjson(param_json, 'SimplifyCell', 1);
prep_series(...
    prep_mat, ...
    pp.image_dir.value, ...
    pp.exp_files.value, ...
    pp.view.value, ...
    pp.woco_xw.value, ...
    pp.woco_yw.value, ...
    pp.woco_xp.value, ...
    pp.woco_yp.value, ...
    pp.crop_xlim.value, ...
    pp.crop_ylim.value, ...
    pp.crop_npts.value, ...
    pp.mask_poly.value, ...
    pp.mask_hue_lim.value, ...
    pp.mask_value_lim.value, ...
    pp.mask_entropy_lim.value, ...
    pp.mask_entropy_len.value, ...
    pp.mask_morph_open_rad.value, ...
    pp.mask_morph_erode_rad.value, ...
    pp.intensity_eql_len.value, ...
    pp.notes.value);
