function display_piv_from_file(filename, idx, prefix)
% function display_piv_from_file(filename, idx, prefix)
%
% Arguments:
%   filename: data file name, as generated by prep()
%   idx: index of step to display
%   prefix: String, optional prefix for subplot titles, defaults to
%       "Step %d:"
% %

narginchk(2, 3);

input_data = matfile(filename, 'Writable', false);

if nargin < 3; prefix = sprintf('Step %d:', input_data.step(idx, 1)); end

piv_result = struct(...
    'x', reshape(input_data.x, [1, length(input_data.x)]), ...
    'y', reshape(input_data.y, [length(input_data.y), 1]),...
    'u', input_data.u(:, :, idx), ...
    'v', input_data.v(:, :, idx), ...
    'mask', input_data.mask(:, :, idx), ...
    'quality', input_data.quality(:, :, idx));

display_piv(piv_result, prefix);