function display_image_pair_from_file(filename, ini_idx, fin_idx)
% function display_image_pair_from_file(filename, ini_idx, fin_idx)
%
% Simple plot of image pair with area outside ROI set to 0
%
% Arguments:
%   filename: data file name, as generated by prep()
%   ini_idx, fin_idx: index of first, last images in pair
% %

% TODO: add option to include padding in display

data = matfile(filename, 'Writable', false);

 display_image_pair(...
     data.x, ...
     data.y, ...
     data.img(:, :, :, ini_idx), ...
     data.mask(:, :, ini_idx), ...
     data.img(:, :, :, fin_idx), ...
     data.mask(:, :, fin_idx));