function display_image_pair_from_file(filename, ini_idx, fin_idx, which, pad_method)
% function display_image_pair_from_file(filename, ini_idx, fin_idx, which, pad_method)
%
% Simple plot of image pair with area outside ROI set to 0
%
% Arguments:
%   filename: data file name, as generated by prep()
%   ini_idx, fin_idx: index of first, last images in pair
%   which: Optional string, select which kind of display, options are
%       'subplot' and 'toggle' 
%   pad_method: Optional string, if provided apply specified boundary
%       padding method, see options in piv_fill
% %

% TODO: add option to include padding in display

data = matfile(filename, 'Writable', false);

 display_image_pair(...
     data.x, ...
     data.y, ...
     data.img(:, :, :, ini_idx), ...
     data.mask(:, :, ini_idx), ...
     data.img(:, :, :, fin_idx), ...
     data.mask(:, :, fin_idx), ...
     which, ...
     pad_method);